Reformat

diff --git a/bin/dot-link-files b/bin/dot-link-files
--- a/bin/dot-link-files
+++ b/bin/dot-link-files
@@ -1,36 +1,36 @@
 #!/usr/bin/env bash
 
 if [ -z "$DOTFILES_PATH" ]; then
-    echo 'Abort: Expected $DOTFILES_PATH to be set'
-    exit 1
+  echo 'Abort: Expected $DOTFILES_PATH to be set'
+  exit 1
 fi
 
 # Hidden files
 declare -a files=(
-    gitconfig
-    gitignore
-    eslintrc
-    inputrc
-    tmux.conf
-    vim
-    vimrc
-    replyrc
-    prettier
-    gemrc
-    ripgreprc
+  gitconfig
+  gitignore
+  eslintrc
+  inputrc
+  tmux.conf
+  vim
+  vimrc
+  replyrc
+  prettier
+  gemrc
+  ripgreprc
 )
 
 for i in ${files[@]}; do
-    # create symbolic link if not exists
-    [ -L $HOME/.$i ] || ln -sv $DOTFILES_PATH/$i $HOME/.$i
+  # create symbolic link if not exists
+  [ -L $HOME/.$i ] || ln -sv $DOTFILES_PATH/$i $HOME/.$i
 done
 
 # Normal files
 declare -a files=(
-    tsconfig.json
+  tsconfig.json
 )
 
 for i in ${files[@]}; do
-    # create symbolic link if not exists
-    [ -L $HOME/$i ] || ln -sv $DOTFILES_PATH/$i $HOME/$i
+  # create symbolic link if not exists
+  [ -L $HOME/$i ] || ln -sv $DOTFILES_PATH/$i $HOME/$i
 done
